export default {
  NEWS_REFRESH: "NEWS_REFRESH",
  NEWS_REFRESH_FAIL: "NEWS_REFRESH_FAIL",
  NEWS_REFRESH_SUCCESS: "NEWS_REFRESH_SUCCESS",
  NEWS_LOAD_MORE_SUCCESS: "NEWS_LOAD_MORE_SUCCESS",
  NEWS_LOAD_MORE_FAIL: "NEWS_LOAD_MORE_FAIL",
  FLUSH_NEWS_FAVORITE: "FLUSH_NEWS_FAVORITE",
}