export default {
  NEWS_REFRESH: 'NEWS_REFRESH',
  NEWS_REFRESH_FAIL: 'NEWS_REFRESH_FAIL',
  NEWS_REFRESH_SUCCESS: 'NEWS_REFRESH_SUCCESS',
  NEWS_LOAD_MORE_SUCCESS: 'NEWS_LOAD_MORE_SUCCESS',
  NEWS_LOAD_MORE_FAIL: 'NEWS_LOAD_MORE_FAIL',
  FLUSH_NEWS_FAVORITE: 'FLUSH_NEWS_FAVORITE',
  // lesson 版块 -- 视频
  VIDEO_REFRESH: 'VIDEO_REFRESH',
  VIDEO_REFRESH_FILE: 'VIDEO_REFRESH_FILE',
  VIDEO_REFRESH_SUCCESS: 'VIDEO_REFRESH_SUCCESS',
  VIDWO_LOAD_MORE_FILE: 'VIDWO_LOAD_MORE_FILE',
  VIDWO_LOAD_MORE_SUCCESS: 'VIDWO_LOAD_MORE_SUCCESS',
  // lesson 版块 -- 名师
};
